<?php session_start();  include('mypanel/config.inc');  require_once('jdf.php'); $resprofile=mysql_query("select * from site_profile"); $fetprofile=mysql_fetch_array($resprofile);?>
<!DOCTYPE html>
<html lang="fa">
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Product",
  "name" : "باستینک",
  "image" : [ "http://www.bastink.com/assets/img/banner/1591723158.jpg", "http://www.bastink.com/assets/img/banner/1591721915.jpg", "http://www.bastink.com/assets/img/banner/1591722847.jpg", "http://www.bastink.com/assets/img/banner/1591722401.jpg", "http://www.bastink.com/images/products/thumb_1641747131.jpg", "http://www.bastink.com/images/products/thumb_1641750592.jpg", "http://www.bastink.com/images/products/thumb_1641748805.jpg", "http://www.bastink.com/images/products/thumb_1641750898.jpg", "http://www.bastink.com/images/products/thumb_1641750446.jpg", "http://www.bastink.com/images/products/thumb_1635611761.jpg", "http://www.bastink.com/images/products/thumb_1635612854.jpg", "http://www.bastink.com/images/products/thumb_1592461414.jpg", "http://www.bastink.com/images/products/thumb_yigpq_dena.jpg" ],
  "description" : "فروش لوازم و تجهیزات ساختمان",
  "brand" : {
    "@type" : "Brand",
    "name" : "استیل البرز"
  },
  "aggregateRating" : {
    "@type" : "AggregateRating",
    "bestRating" : "100"
  },
  "review" : {
    "@type" : "Review",
    "reviewRating" : {
      "@type" : "Rating",
      "ratingValue" : "20"
    }
  }
}
</script>
<style>
@media (min-width: 992px){
    .banner-ads .col-lg-3 {
        -ms-flex: 0 0 10%;
        flex: 0 0 10%;
        max-width: 10%;
    }
}
</style>
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="favicon.png">
    <link rel="icon" type="image/png" href="favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <link href="favicon.ico" rel="icon" />
    <title><?php echo $fetprofile['fa_title']; ?></title>
    <meta name="description" content="<?php echo $fetprofile['fa_title'].', '.$fetprofile['en_title'].', '.$fetprofile['keywords'];?>و <?php include('mypanel/config.inc'); @$res=mysql_query("select * from menu order by id"); while(@$fet=mysql_fetch_array($res)) echo ",$fet[title] "; @$res=mysql_query("select DISTINCT title from product_category order by title"); while(@$fet=mysql_fetch_array($res)) echo ",$fet[title] "; @$res=mysql_query("select DISTINCT title from brands order by title"); while(@$fet=mysql_fetch_array($res)) echo ",محصولات $fet[title] "; @$res=mysql_query("select DISTINCT title from search_list order by title"); while(@$fet=mysql_fetch_array($res)) echo ", $fet[title] "?>">
    <meta name="keywords" content="<?php echo $fetprofile['fa_title'].', '.$fetprofile['en_title'].', '.$fetprofile['keywords'];?>و <?php include('mypanel/config.inc'); @$res=mysql_query("select * from menu order by id"); while(@$fet=mysql_fetch_array($res)) echo ",$fet[title] "; @$res=mysql_query("select DISTINCT title from product_category order by title"); while(@$fet=mysql_fetch_array($res)) echo ",$fet[title] "; @$res=mysql_query("select DISTINCT title from brands order by title"); while(@$fet=mysql_fetch_array($res)) echo ",محصولات $fet[title] "; @$res=mysql_query("select DISTINCT title from search_list order by title"); while(@$fet=mysql_fetch_array($res)) echo ", $fet[title] "?>">
    <!--     Fonts and icons     -->
    <link rel="stylesheet" href="assets/fonts/font-awesome/css/font-awesome.min.css" />
    <!-- CSS Files -->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="assets/css/now-ui-kit.css" rel="stylesheet" />
    <link href="assets/css/plugins/owl.carousel.css" rel="stylesheet" />
    <link href="assets/css/plugins/owl.theme.default.min.css" rel="stylesheet" />
    <link href="assets/css/main.css" rel="stylesheet" />
</head>
<body class="index-page sidebar-collapse">
    
        <?php include('header1.php');?>

        <main class="main default">
            <div class="container">
                <div class="row">
                   
                    <div class="col-12 col-lg-12 order-1 order-lg-2">
                             <?php $res=mysql_query("select * from message order by sort ASC"); 
                                if(mysql_num_rows($res)) {
                                    echo'<div class="alert alert-info" role="alert" style="margin:0 0 20px 0;background:rgb(21 125 47);">';
                                    while($fet=mysql_fetch_array($res)){
                        		        echo '<li><i class="now-ui-icons travel_info"></i> '.$fet['message'].'</li>';
                            	    }
                        	        echo'</div>';
                                }
                    		 ?>
                         <section id="main-slider" class="carousel slide carousel-fade card" data-ride="carousel">
                            <ol class="carousel-indicators">
                    	    <?php $i=0; $res=mysql_query("select * from slides where state=1 and pos=0 order by rand()"); while($fet=mysql_fetch_array($res)) {
			                    echo '<li data-target="#main-slider" data-slide-to="'.$i.'"'; if($i==0) echo' class="active"';echo'></li>';
			                    $i++;
                    	    }
		                    ?>
                            </ol>
                            <div class="carousel-inner">
                                <?php $j=0; $res=mysql_query("select * from slides where state=1 and pos=0 order by  rand()"); while($fet=mysql_fetch_array($res)) {
                                echo '<div class="carousel-item';if($j==0) echo' active';echo'">
                                        <a class="d-block" href="'.$fet['link'].'">
                                            <img src="assets/img/banner/'.$fet['imgurl'].'" alt="'.$fet['title'].'" class="d-block w-100">
                                        </a>
                                     </div>';
                                $j++;
                                }
                                ?>
                            </div>
                            <a class="carousel-control-prev" href="#main-slider" role="button" data-slide="prev">
                                <i class="now-ui-icons arrows-1_minimal-right"></i>
                            </a>
                            <a class="carousel-control-next" href="#main-slider" data-slide="next">
                                <i class="now-ui-icons arrows-1_minimal-left"></i>
                            </a>
                        </section>

                        <div class="row banner-ads">
                            <div class="col-12">
                                <div class="row">
                                    <?php $res=mysql_query("select * from slides where state=1 and pos=4 order by rand()"); while($fet=mysql_fetch_array($res)) {
                                    echo'<div class="col-12">
                                            <div class="widget widget-banner card">
                                                <a href="'.$fet['link'].'">
                                                    <img src="assets/img/banner/'.$fet['imgurl'].'" alt="'.$fet['title'].'" title="'.$fet['title'].'" class="img-fluid">
                                                </a>
                                            </div>
                                        </div>';
                                    }
                                    ?>
                                </div>
                            </div>
                        </div> 
    <?php
	
		$res1=mysql_query("select * from product_categorys where level=2 and state=1 limit 16");
		$i=mysql_num_rows($res1);
		$j=floor($i/2);
		$res1=mysql_query("select * from product_category where level=2 and state=1 limit $j");
		while($fet1=mysql_fetch_array($res1)){ 
			$res2=mysql_query("select * from product_category where parent_id=".$fet1['id']." and state=1 order by rand()");
                    echo '<div class="row">
                            <div class="col-12">
                                <div class="widget widget-product card">
                                    <header class="card-header">
                                        <h3 class="card-title">
                                            <span>'.$fet1['title'].'</span>
                                        </h3>
                                    </header>
                                    <div class="product-carousel owl-carousel owl-theme">';
			                        while($fet2=mysql_fetch_array($res2)){ 
                                        $res3=mysql_query("select * from product_option where product_id=".$fet2['id']." group by product_id order by RAND()");
                							while($fet3=mysql_fetch_array($res3)){ 
                    							$res_cat=mysql_query("select * from product_option where id=".$fet3['id']." group by product_id order by rand()");
                    							$fet_cat=mysql_fetch_array($res_cat);
                    							$company_id=$fet_cat['company_id'];
                    							$res_cat0=mysql_query("select * from product_category where id=".$company_id);
                    							$fet_cat0=mysql_fetch_array($res_cat0);
                    							$company_id2=$fet_cat0['parent_id'];
                    							$company_title2=$fet_cat0['title'];
                    							$res_cat1=mysql_query("select * from product_category where id=".$company_id2);
                    							$fet_cat1=mysql_fetch_array($res_cat1);
                    							$product_id2=$fet_cat1['parent_id'];
                    							$product_title2=$fet_cat1['title'];
                								$off=(($fet3['off']+$fet3['extraOff'])/100)*$fet3['price'];
                								if($fet3['offType'])
                								$off = $fet3['price'];
                								else
                								$off = $fet3['price']-$off;
								                switch(strlen($fet3['price'])){ 
                									case 1:
                									case 2:
                									case 3:
                										$price = round($fet3['price'] / 10) * 10;
                										$off = round($off / 10) * 10;
                									break;
                									case 4:	
                										$price = round($fet3['price'] / 10) * 10;
                										$off = round($off / 10) * 10;
                									break;
                									case 5:	
                									    $price = round($fet3['price'] / 100) * 100;
                										$off = round($off / 100) * 100;
                									break;
                									case 6:	
                									case 7:	
                										$price = ceil($fet3['price'] / 1000) * 1000;
                										$off = ceil($off / 1000) * 1000;
                									break;
                									case 8:	
                									case 9:	
                										$price = ceil($fet3['price'] / 10000) * 10000;
                										$off = ceil($off / 10000) * 10000;
                									break;
                								}
                								$res4=mysql_query("SELECT * FROM images where category LIKE 'products' and row_id=".$fet3['item_id']." ORDER BY (state = 1) DESC");
							                    $fet4=mysql_fetch_array($res4);
            								    echo'<div class="item">
                                                        <a href="result.php?pid=1&product_id='.$fet3['product_id'].'&name='.$product_title2.'">
                                                            <img src="images/products/thumb_'.$fet4['file_name'].'" class="img-fluid" alt="مشخصات، قیمت و خرید '.$product_title2.'">
                                                        </a>
                                                        <h5 class="btn-danger" style="margin-top:10px;border-radius:5px;font-size:17px;padding:10px 0;">
                                                            <a href="result.php?pid=1&product_id='.$fet3['product_id'].'&name='.$product_title2.'" style="color:#fff">'.$product_title2.'</a>
                                                        </h5>
                                                        <div class="price" style="display:none"><br/>';
                                                            if(!$fet3['offType'] && $fet3['off']<>0) echo'<span class="discount-percent" style="background: #ff6600; color: #fff; display: inline-block; padding: 4px 14px; border-radius: 40px; font-size:14px;float:none">'.number_format($fet3['off']+$fet3['extraOff']).'% تخفیف</span>
                                                            <div class="text-center">
                                                                <del><span>'.number_format($price).' <span>تومان</span></span></del>
                                                            </div>';
                                                            else echo'<br/>';
                                                            echo'<div class="text-center">
                                                                <ins><span>'.number_format($off).' <span>تومان</span></span></ins>
                                                            </div>
                                                        </div>
                                                    </div>';
				
			                                }
			                        }
                                    echo'</div>
                                </div>
                            </div>
                        </div>';
        }
	?>
	      
	                    
    
    <?php
    
         echo '<div class="row">
                            <div class="col-12">
                                <div class="widget widget-product card">
                                    <header class="card-header">
                                        <h3 class="card-title">
                                            <span>محصولات جدید</span>
                                        </h3>
                                    </header>
                                    <div class="product-carousel owl-carousel owl-theme">';
			                        
                                        $res3=mysql_query("select * from product_option where seller_id<>0 and parent_id=0 and stoke=1 order by rand() DESC LIMIT 20");
                                       
                							while($fet_cat=mysql_fetch_array($res3)){ 
                    							
                    							$company_id=$fet_cat['company_id'];
                    							$res_cat0=mysql_query("select * from product_category where id=".$company_id);
                    							$fet_cat0=mysql_fetch_array($res_cat0);
                    							$company_id1=$fet_cat0['parent_id'];
                    							$company_title1=$fet_cat0['title'];
                    							$res_cat1=mysql_query("select * from product_category where id=".$company_id1);
                    							$fet_cat1=mysql_fetch_array($res_cat1);
                    							$product_id1=$fet_cat0['parent_id'];
                    							$product_title1=$fet_cat1['title'];
                    							$res_pro=mysql_query("select * FROM product_option 
                        							INNER JOIN product_template_option ON product_option.option_id = product_template_option.id
                        							INNER JOIN pro_options ON product_template_option.option_id = pro_options.id
                        							where product_option.item_id=".$fet_cat['item_id']." and product_template_option.option_id=181");
                        							$fet_pro = mysql_fetch_array($res_pro);	$model=$fet_pro['val'];
                								
                    							
                    							$off=(($fet_cat['off'])/100)*$fet_cat['val'];
                    							
                
                    								$off = $fet_cat['val']-$off;
                    								switch(strlen($fet_cat['price'])){ 
                    									case 1:
                    									case 2:
                    									case 3:
                    										$price = round($fet_cat['val'] / 10) * 10;
                    										$off = round($off / 10) * 10;
                    									break;
                    									case 4:	
                    										$price = round($fet_cat['val'] / 10) * 10;
                    										$off = round($off / 10) * 10;
                    									break;
                    									case 5:	
                    									    $price = round($fet_cat['val'] / 100) * 100;
                    										$off = round($off / 100) * 100;
                    									break;
                    									case 6:	
                    									case 7:	
                    										$price = ceil($fet_cat['val'] / 1000) * 1000;
                    										$off = ceil($off / 1000) * 1000;
                    									break;
                    									case 8:	
                    									case 9:	
                    										$price = ceil($fet_cat['val'] / 10000) * 10000;
                    										$off = ceil($off / 10000) * 10000;
                    									break;
                    								}
                    							$name=$product_title1.'-'.$company_title1.'-مدل-'.$model;
							                    $name=str_replace(" ", "-", $name);	
							                    
                								$res4=mysql_query("SELECT * FROM images where category LIKE 'products' and row_id=".$fet_cat['item_id']." ORDER BY (state = 1) DESC");
							                    $fet4=mysql_fetch_array($res4);
            								    echo'<div class="item">';
            								        if($fet_cat['off']) echo'<del style="clear:both;width:40%;position:absolute;top:5px;right:0;"><span class="badge badge-success" style="background:#2ecc71;color:#fff;padding:6px 8px;margin:0;font-size:20px;border-radius:30px;">%'.$fet_cat['off'].'</span></del>';
                                                        echo'<a href="product.php?pro_id='.$product_id1.'&item='.$fet_cat['item_id'].'&name='.$name.'">
                                                            <img src="images/products/thumb_'.$fet4['file_name'].'" class="img-fluid" alt="مشخصات، قیمت و خرید '.$product_title1.' '.$company_title1.' '.$model.'" title="مشخصات، قیمت و خرید '.$product_title1.' '.$company_title1.' مدل '.$model.'">
                                                        </a>
                                                        <div class="price" style="width:100%;">
                                                            <span style="color:#000;font-size:12px;">'.$product_title1.' '.$company_title1.' مدل '.$model.'</span><br/>';
                                                                echo'<span style="';if($fet_cat['off']) echo'width:60%';else echo'width:100%';echo'">';
                                                                if($fet_cat['off']) echo'<span style="text-decoration:line-through;font-size:14px;color:#ff6600;">'.number_format($price).' تومان</span> ';
                                                                echo'<span style="font-size:14px;color:#2ecc71">'.number_format($off).' تومان</span>
                                                            </span>
                                                        </div>
                                                    </div>';
			                                }
			                        
                                    echo'</div>
                                </div>
                            </div>
                        </div>';

    
            $res1=mysql_query("select * from product_categorys where level=2 and state=1 limit 16");
    		$i=mysql_num_rows($res1);
    		$j=floor($i/2);
    		$k=$i-$j;
    		$res1=mysql_query("select * from product_category where level=2 and state=1 limit $j, $k");
    		while($fet1=mysql_fetch_array($res1)){ 
    			$res2=mysql_query("select * from product_category where parent_id=$fet1[id] and state=1 order by id");
                        echo '<div class="row">
                                <div class="col-12">
                                    <div class="widget widget-product card">
                                        <header class="card-header">
                                            <h3 class="card-title">
                                                <span>'.$fet1['title'].'</span>
                                            </h3>
                                        </header>
                                        <div class="product-carousel owl-carousel owl-theme">';
    			                         while($fet2=mysql_fetch_array($res2)){ 
                                            $res3=mysql_query("select * from product_option where product_id=".$fet2['id']." group by product_id order by RAND()");
                    							while($fet3=mysql_fetch_array($res3)){ 
                        							$res_cat=mysql_query("select * from product_option where id=".$fet3['id']." group by product_id order by rand()");
                        							$fet_cat=mysql_fetch_array($res_cat);
                        							$company_id=$fet_cat['company_id'];
                        							$res_cat0=mysql_query("select * from product_category where id=".$company_id);
                        							$fet_cat0=mysql_fetch_array($res_cat0);
                        							$company_id2=$fet_cat0['parent_id'];
                        							$company_title2=$fet_cat0['title'];
                        							$res_cat1=mysql_query("select * from product_category where id=".$company_id2);
                        							$fet_cat1=mysql_fetch_array($res_cat1);
                        							$product_id2=$fet_cat1['parent_id'];
                        							$product_title2=$fet_cat1['title'];
                    								$off=(($fet3['off']+$fet3['extraOff'])/100)*$fet3['price'];
                    								if($fet3['offType'])
                    								$off = $fet3['price'];
                    								else
                    								$off = $fet3['price']-$off;
    								                switch(strlen($fet3['price'])){ 
                    									case 1:
                    									case 2:
                    									case 3:
                    										$price = round($fet3['price'] / 10) * 10;
                    										$off = round($off / 10) * 10;
                    									break;
                    									case 4:	
                    										$price = round($fet3['price'] / 10) * 10;
                    										$off = round($off / 10) * 10;
                    									break;
                    									case 5:	
                    									    $price = round($fet3['price'] / 100) * 100;
                    										$off = round($off / 100) * 100;
                    									break;
                    									case 6:	
                    									case 7:	
                    										$price = ceil($fet3['price'] / 1000) * 1000;
                    										$off = ceil($off / 1000) * 1000;
                    									break;
                    									case 8:	
                    									case 9:	
                    										$price = ceil($fet3['price'] / 10000) * 10000;
                    										$off = ceil($off / 10000) * 10000;
                    									break;
                    								}
                    								$res4=mysql_query("SELECT * FROM images where category LIKE 'products' and row_id=".$fet3['item_id']." ORDER BY (state = 1) DESC");
    							                    $fet4=mysql_fetch_array($res4);
                								    echo'<div class="item">
                                                            <a href="result.php?pid=1&product_id='.$fet3['product_id'].'&name='.$product_title2.'">
                                                                <img src="images/products/thumb_'.$fet4['file_name'].'" class="img-fluid" alt="مشخصات، قیمت و خرید '.$product_title2.'">
                                                            </a>
                                                            <h5 class="btn-danger" style="margin-top:10px;border-radius:5px;font-size:17px;padding:10px 0;">
                                                                <a href="result.php?pid=1&product_id='.$fet3['product_id'].'&name='.$product_title2.'" style="color:#fff">'.$product_title2.'</a>
                                                            </h5>
                                                            <div class="price" style="display:none"><br/>';
                                                                if(!$fet3['offType'] && $fet3['off']<>0) echo'<span class="discount-percent" style="background: #ff6600; color: #fff; display: inline-block; padding: 4px 14px; border-radius: 40px; font-size:14px;float:none">'.number_format($fet3['off']+$fet3['extraOff']).'% تخفیف</span>
                                                                <div class="text-center">
                                                                    <del><span>'.number_format($price).' <span>تومان</span></span></del>
                                                                </div>';
                                                                else echo'<br/>';
                                                                echo'<div class="text-center">
                                                                    <ins><span>'.number_format($off).' <span>تومان</span></span></ins>
                                                                </div>
                                                            </div>
                                                        </div>';
    				
    			                                }
    			                        }
                                        echo'</div>
                                    </div>
                                </div>
                            </div>';
            }
            ?>
            <div class="row banner-ads">
                            <div class="col-12">
                                <div class="row">
                                    <?php $res=mysql_query("select * from slides where state=1 and pos=3 order by rand()"); while($fet=mysql_fetch_array($res)) {
                                    echo'<div class="col-12 col-lg-6">
                                            <div class="widget-banner card">
                                                <a href="'.$fet['link'].'">
                                                    <img src="assets/img/banner/'.$fet['imgurl'].'" alt="'.$fet['title'].'" title="'.$fet['title'].'" class="img-fluid">
                                                </a>
                                            </div>
                                        </div>';
                                    }
                                    ?>
                                </div>
                            </div>
                        </div> 
            <?php
          echo '<div class="row">
                            <div class="col-12">
                                <div class="widget widget-product card">
                                    <header class="card-header">
                                        <h3 class="card-title">
                                            <span>پیشنهاد ویژه</span>
                                        </h3>
                                    </header>
                                    <div class="product-carousel owl-carousel owl-theme">';
			                        
                                        $res3=mysql_query("select * from product_option where seller_id<>0 and stoke=1 and off>10 order by RAND() LIMIT 20");
                                       
                							while($fet_cat=mysql_fetch_array($res3)){ 
                    							
                    							$company_id=$fet_cat['company_id'];
                    							$res_cat0=mysql_query("select * from product_category where id=".$company_id);
                    							$fet_cat0=mysql_fetch_array($res_cat0);
                    							$company_id1=$fet_cat0['parent_id'];
                    							$company_title1=$fet_cat0['title'];
                    							$res_cat1=mysql_query("select * from product_category where id=".$company_id1);
                    							$fet_cat1=mysql_fetch_array($res_cat1);
                    							$product_id1=$fet_cat0['parent_id'];
                    							$product_title1=$fet_cat1['title'];
                    							$res_pro=mysql_query("select * FROM product_option 
                        							INNER JOIN product_template_option ON product_option.option_id = product_template_option.id
                        							INNER JOIN pro_options ON product_template_option.option_id = pro_options.id
                        							where product_option.item_id=".$fet_cat['item_id']." and product_template_option.option_id=181");
                        							$fet_pro = mysql_fetch_array($res_pro);	$model=$fet_pro['val'];
                								
                    							
                    							$off=(($fet_cat['off'])/100)*$fet_cat['val'];
                    							
                
                    								$off = $fet_cat['val']-$off;
                    								switch(strlen($fet_cat['price'])){ 
                    									case 1:
                    									case 2:
                    									case 3:
                    										$price = round($fet_cat['val'] / 10) * 10;
                    										$off = round($off / 10) * 10;
                    									break;
                    									case 4:	
                    										$price = round($fet_cat['val'] / 10) * 10;
                    										$off = round($off / 10) * 10;
                    									break;
                    									case 5:	
                    									    $price = round($fet_cat['val'] / 100) * 100;
                    										$off = round($off / 100) * 100;
                    									break;
                    									case 6:	
                    									case 7:	
                    										$price = ceil($fet_cat['val'] / 1000) * 1000;
                    										$off = ceil($off / 1000) * 1000;
                    									break;
                    									case 8:	
                    									case 9:	
                    										$price = ceil($fet_cat['val'] / 10000) * 10000;
                    										$off = ceil($off / 10000) * 10000;
                    									break;
                    								}
                    							$name=$product_title1.'-'.$company_title1.'-مدل-'.$model;
							                    $name=str_replace(" ", "-", $name);	
							                    
                								$res4=mysql_query("SELECT * FROM images where category LIKE 'products' and row_id=".$fet_cat['item_id']." ORDER BY (state = 1) DESC");
							                    $fet4=mysql_fetch_array($res4);
            								    echo'<div class="item">';
            								        if($fet_cat['off']) echo'<del style="clear:both;width:40%;position:absolute;top:5px;right:0;"><span class="badge badge-success" style="background:#2ecc71;color:#fff;padding:6px 8px;margin:0;font-size:20px;border-radius:30px;">%'.$fet_cat['off'].'</span></del>';
                                                        echo'<a href="product.php?pro_id='.$product_id1.'&item='.$fet_cat['item_id'].'&name='.$name.'"">
                                                            <img src="images/products/thumb_'.$fet4['file_name'].'" class="img-fluid" alt="مشخصات، قیمت و خرید '.$product_title1.' '.$company_title1.' '.$model.'" title="مشخصات، قیمت و خرید '.$product_title1.' '.$company_title1.' مدل '.$model.'">
                                                        </a>
                                                        <div class="price" style="width:100%;">
                                                            <span style="color:#000;font-size:12px;">'.$product_title1.' '.$company_title1.' مدل '.$model.'</span><br/>';
                                                                echo'<span style="';if($fet_cat['off']) echo'width:60%';else echo'width:100%';echo'">';
                                                                if($fet_cat['off']) echo'<span style="text-decoration:line-through;font-size:14px;color:#ff6600;">'.number_format($price).' تومان</span> ';
                                                                echo'<span style="font-size:14px;color:#2ecc71">'.number_format($off).' تومان</span>
                                                            </span>
                                                        </div>
                                                    </div>';
				
			                                }
			                        
                                    echo'</div>
                                </div>
                            </div>
                        </div>';
       
	?>
	
                        
                        
                        
                    </div>
                </div>
                
                <div class="row banner-ads" style="display:none">
                    <div class="col-12">
                        <div class="row">
                            <div class="col-12">
                                <div class="widget widget-banner card" style="background:none;">
                                        <video controls style="width: 100%; height: auto; border-radius:8px;padding:0;" poster="assets/tizer-cover1.jpg"><source src="assets/tizer1.mp4" type="video/mp4"></video>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </main>

        <?php include('footer1.php');?>
        
    </div>
</body>
</html>
<!--   Core JS Files   -->
<script src="assets/js/core/jquery.3.2.1.min.js" type="text/javascript"></script>
<script src="assets/js/core/popper.min.js" type="text/javascript"></script>
<script src="assets/js/core/bootstrap.min.js" type="text/javascript"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="assets/js/plugins/bootstrap-switch.js"></script>
<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="assets/js/plugins/nouislider.min.js" type="text/javascript"></script>
<!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker -->
<script src="assets/js/plugins/bootstrap-datepicker.js" type="text/javascript"></script>
<!-- Share Library etc -->
<script src="assets/js/plugins/jquery.sharrre.js" type="text/javascript"></script>
<!-- Control Center for Now Ui Kit: parallax effects, scripts for the example pages etc -->
<script src="assets/js/now-ui-kit.js" type="text/javascript"></script>
<!--  CountDown -->
<script src="assets/js/plugins/countdown.min.js" type="text/javascript"></script>
<!--  Plugin for Sliders -->
<script src="assets/js/plugins/owl.carousel.min.js" type="text/javascript"></script>
<!--  Jquery easing -->
<script src="assets/js/plugins/jquery.easing.1.3.min.js" type="text/javascript"></script>
<!-- Main Js -->
<script src="assets/js/main.js" type="text/javascript"></script>